/* Stable, machine-readable error codes. These appear in every error envelope (`error.code`) and are consumed by the */
export const ERROR_CODES = {
  // Transport / framework
  UNKNOWN: "ERR_UNKNOWN",
  VALIDATION: "ERR_VALIDATION",
  NOT_FOUND: "ERR_NOT_FOUND",
  CONFLICT: "ERR_CONFLICT",
  UNAUTHORIZED: "ERR_UNAUTHORIZED",
  FORBIDDEN: "ERR_FORBIDDEN",
  TOO_MANY_REQUESTS: "ERR_TOO_MANY_REQUESTS",
  INTERNAL: "ERR_INTERNAL",

  // Database
  DATABASE_CONNECTION: "ERR_DB_CONNECTION",
  RECORD_NOT_FOUND: "ERR_DB_RECORD_NOT_FOUND",
  UNIQUE_VIOLATION: "ERR_DB_UNIQUE_VIOLATION",
  FOREIGN_KEY_VIOLATION: "ERR_DB_FOREIGN_KEY_VIOLATION",

  // Domain
  ORGANIZATION_NOT_FOUND: "ERR_ORG_NOT_FOUND",
  WORKSPACE_NOT_FOUND: "ERR_WORKSPACE_NOT_FOUND",
  TENANT_MISMATCH: "ERR_TENANT_MISMATCH",

  // Pipeline & engines
  PIPELINE: "ERR_PIPELINE",
  PIPELINE_VALIDATION: "ERR_PIPELINE_VALIDATION",
  PIPELINE_AUTHORIZATION: "ERR_PIPELINE_AUTHORIZATION",
  PIPELINE_ENTRY: "ERR_PIPELINE_ENTRY",
  PIPELINE_TIMEOUT: "ERR_PIPELINE_TIMEOUT",
  TRAVERSAL: "ERR_TRAVERSAL",
  PERMISSION: "ERR_PERMISSION",
  RULE_ENGINE: "ERR_RULE_ENGINE",
  RULE_ENGINE_CONFIG: "ERR_RULE_ENGINE_CONFIG",
  RULE_EXECUTION: "ERR_RULE_EXECUTION",
  CANDIDATE: "ERR_CANDIDATE",
  CANDIDATE_RANKING: "ERR_CANDIDATE_RANKING",
  CONTEXT_ASSEMBLY: "ERR_CONTEXT_ASSEMBLY",
  CONFIGURATION: "ERR_CONFIGURATION",

  // Graph engine
  GRAPH_NODE_NOT_FOUND: "ERR_GRAPH_NODE_NOT_FOUND",
  GRAPH_ENTRY_NOT_FOUND: "ERR_GRAPH_ENTRY_NOT_FOUND",
  GRAPH_CYCLE_DETECTED: "ERR_GRAPH_CYCLE_DETECTED",
  GRAPH_INVALID: "ERR_GRAPH_INVALID",
  GRAPH_INVALID_EDGE: "ERR_GRAPH_INVALID_EDGE",
  GRAPH_SELF_REFERENCE: "ERR_GRAPH_SELF_REFERENCE",
  GRAPH_TRAVERSAL: "ERR_GRAPH_TRAVERSAL",

  // Authorization engine
  PERMISSION_DENIED: "ERR_PERMISSION_DENIED",
  AUTHORIZATION_COMPILE: "ERR_AUTHZ_COMPILE",
  AUTHORIZATION_CONTEXT_MISSING: "ERR_AUTHZ_CONTEXT_MISSING",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
